# Generated by Django 5.2.6 on 2025-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'teacher'},
        ),
        migrations.CreateModel(
            name='schoolmanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('student', models.ManyToManyField(to='myapp.student')),
                ('teacher', models.ManyToManyField(to='myapp.teacher')),
            ],
        ),
    ]
