# Generated by Django 5.2.7 on 2025-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teacher_options_schoolmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to='scope'),
        ),
    ]
