# Generated by Django 5.2.6 on 2025-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to='pdffile'),
        ),
    ]
